import { NextRequest, NextResponse } from "next/server";

/**
 * POST /api/topics/recommend
 *
 * Takes a user profile and returns personalized topic recommendations.
 * In production, this calls Claude API with the recommender prompt.
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();

    // Demo recommendations — in production, generated by Claude
    const recommendations = [
      {
        title: "Game Theory for Strategic Decisions in Tech",
        description: "How game theory models apply to product strategy, pricing, and competitive analysis.",
        why_for_you: "Directly applicable to your product decision-making framework.",
        category: "primary",
      },
      {
        title: "The Science of Effective Communication",
        description: "Cognitive science behind persuasion, clarity, and influence in professional settings.",
        why_for_you: "Bridges your technical depth with stakeholder communication.",
        category: "adjacent",
      },
      {
        title: "Fermentation: Science and Art",
        description: "The microbiology, chemistry, and craft of fermented foods across cultures.",
        why_for_you: "A fascinating intersection of biology and culture — great for expanding your thinking patterns.",
        category: "serendipity",
      },
    ];

    return NextResponse.json({ recommendations });
  } catch {
    return NextResponse.json({ error: "Invalid request" }, { status: 400 });
  }
}
